# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_other1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allpublished_in', models.CharField(max_length=10)),
                ('blog', models.ManyToManyField(to='blogging.Blog')),
            ],
        ),
    ]
