# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_other2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('n', 'No')], max_length=20),
        ),
    ]
