# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0006_auto_20180417_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('n', 'No')], default=('y', 'Yes'), max_length=20),
        ),
    ]
