# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0009_auto_20180417_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(),
        ),
    ]
