# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0010_auto_20180418_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(auto_now=True),
        ),
    ]
